{
 "title": "MikroTik Router — RB3011",
 "description": "Mikrotik MKTXP Exporter metrics",
 "tags": [
  "mikrotik",
  "mktxp"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "prom_ds", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "node",
    "label": "Routerboard",
    "query": {
     "query": "label_values(mktxp_system_identity_info, routerboard_name)"
    }
   },
   { "name": "Filters" },
   {
    "name": "instance",
    "query": {
     "query": "label_values(mtxrInterfaceStatsIndex,instance)"
    }
   },
   {
    "name": "Interface",
    "query": {
     "query": "query_result(sort(mtxrInterfaceStatsIndex{ifName=~'^(ether).+',instance='$instance'}) or sort(mtxrInterfaceStatsIndex{ifName=~'^(sfp|wlan).+',instance='$instance'}) or sort(mtxrInterfaceStatsIndex{ifName=~'^bridge.+',instance='$instance'}) or  sort(mtxrInterfaceStatsIndex{ifName!~'^(ether|bridge|mAP|wAP).+',instance='$instance'}) )"
    }
   }
  ]
 },
 "panels": [
  { "title": "📡 NETWORK STATUS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "time() * 1000" }
   ]
  },
  {
   "title": "Router Uptime",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    { "expr": "mktxp_system_uptime" }
   ]
  },
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "count(mktxp_netwatch_status == 1)",
     "legendFormat": "UP"
    },
    {
     "expr": "count(mktxp_netwatch_status == 0)",
     "legendFormat": "DOWN"
    }
   ]
  },
  {
   "title": "📡 NETWORK STATUS",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mktxp_netwatch_status{name=\"8.8.8.8\"}",
     "legendFormat": "WAN"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"1.1.1.1\"}",
     "legendFormat": "WAN-2"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"10.10.10.2\"}",
     "legendFormat": "Server1"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"10.20.20.2\"}",
     "legendFormat": "Server2"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"10.20.20.3\"}",
     "legendFormat": "AMP"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"10.30.30.10\"}",
     "legendFormat": "iDRAC1"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"10.30.30.11\"}",
     "legendFormat": "iDRAC2"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"10.60.60.200\"}",
     "legendFormat": "mAP2nD-1"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"10.60.60.201\"}",
     "legendFormat": "wAP2nD-1"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"10.40.40.2\"}",
     "legendFormat": "RPi"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"172.17.0.2\"}",
     "legendFormat": "Pi-hole"
    }
   ]
  },
  { "title": "System", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mktxp_system_cpu_load{routerboard_name=\"$node\"}",
     "legendFormat": "CPU"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mktxp_system_routerboard_temperature{routerboard_name=\"$node\"}  ",
     "legendFormat": "__auto"
    },
    {
     "expr": "mktxp_system_cpu_temperature{routerboard_name=\"$node\"}  ",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - mktxp_system_free_memory{routerboard_name=\"$node\"} / mktxp_system_total_memory{routerboard_name=\"$node\"}) * 100",
     "legendFormat": "RAM"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - mktxp_system_free_hdd_space{routerboard_name=\"$node\"} / mktxp_system_total_hdd_space{routerboard_name=\"$node\"}) * 100",
     "legendFormat": "HDD"
    }
   ]
  },
  {
   "title": "Active Users",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "mktxp_active_users_info{routerboard_name=\"$node\"}"
    }
   ]
  },
  {
   "title": "System uptime",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mktxp_system_uptime{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "System uptime" },
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "System version",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 13 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mktxp_system_uptime{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "System version and hw" },
     "legendFormat": "Current: {{version}} ",
     "mode": 2,
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "mktxp_system_update_available{routerboard_name=\"$node\"}",
     "legendFormat": "Latest available: {{newest_version}}"
    }
   ]
  },
  {
   "title": "CPU load",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "application": { "filter": "CPU" },
     "expr": "mktxp_system_cpu_load{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "CPU 1 load" },
     "legendFormat": "{{cpu}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Identity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mktxp_system_identity_info{routerboard_name=\"$node\"}  ",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "IP Address",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mktxp_public_ip_address_info{routerboard_name=\"$node\"}",
     "legendFormat": "{{routerboard_address}}"
    }
   ]
  },
  {
   "title": "Serial Number",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 19 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrSerialNumber{instance='$instance'}",
     "legendFormat": "{{mtxrSerialNumber}}"
    }
   ]
  },
  {
   "title": "Public Address",
   "type": "stat",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mktxp_public_ip_address_info{routerboard_name=\"$node\"}",
     "legendFormat": "{{public_address}}"
    },
    {
     "expr": "mktxp_public_ip_address_info{routerboard_name=\"$node\"}",
     "legendFormat": "{{dns_name}}"
    }
   ]
  },
  {
   "title": "Routerboard HW",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 22 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mktxp_system_uptime{routerboard_name=\"$node\"}",
     "legendFormat": "{{board_name}}"
    }
   ]
  },
  {
   "title": "Software ID",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 25 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrLicSoftwareId{instance='$instance'}",
     "legendFormat": "{{mtxrLicSoftwareId}}"
    }
   ]
  },
  {
   "title": "Voltage",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "volt" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "General" },
     "expr": "mktxp_system_routerboard_voltage{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "System version and hw" },
     "mode": 2,
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CPU Frequency",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 18, "x": 6, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "expr": "mktxp_system_cpu_frequency{routerboard_name=\"$node\"}*1000000",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Used memory" },
     "legendFormat": "{{cpu}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Installed Packages",
   "type": "table",
   "gridPos": { "h": 15, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "mktxp_installed_packages_info{routerboard_name=\"$node\"}"
    }
   ]
  },
  {
   "title": "HDD Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 18, "x": 6, "y": 37 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "application": { "filter": "Memory" },
     "expr": "mktxp_system_total_hdd_space{routerboard_name=\"$node\"} - mktxp_system_free_hdd_space{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Used memory" },
     "legendFormat": "Used memory",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "Memory" },
     "expr": "mktxp_system_total_hdd_space{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "Total memory" },
     "legendFormat": "Total memory",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "DHCP", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "IP Pool Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 44 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mktxp_ip_pool_used{routerboard_name=\"$node\"} ",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ pool }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "DHCP Leases",
   "type": "table",
   "gridPos": { "h": 19, "w": 19, "x": 5, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "targets": [
    {
     "expr": "mktxp_dhcp_lease_info{routerboard_name=\"$node\"}"
    }
   ]
  },
  {
   "title": "DHCP Leases by Server",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 52 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mktxp_dhcp_lease_active_count{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ server }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Total DHCP Leases",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 60 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "sum(mktxp_dhcp_lease_active_count{routerboard_name=\"$node\"})",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "In - {{ server }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "Network", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 63 } },
  {
   "title": "Total Routes",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 2, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mktxp_routes_total_routes{routerboard_name=\"$node\"}"
    }
   ]
  },
  {
   "title": "Routes per protocol",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 4, "x": 2, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mktxp_routes_protocol_count{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "/errors on interface/" },
     "legendFormat": "{{protocol}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Ethernet Ports: Full Duplex",
   "type": "bargauge",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 64 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mktxp_interface_full_duplex{routerboard_name=\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Interface Errors",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_interface_rx_error_total{routerboard_name=\"$node\"}[4m])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "/errors on interface/" },
     "legendFormat": "In Errors | {{name}}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "rate(mktxp_interface_tx_error_total{routerboard_name=\"$node\"}[4m])",
     "legendFormat": "Out Errors | {{name}}"
    }
   ]
  },
  {
   "title": "Ethernet Ports: Status",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 69 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "mktxp_interface_status{routerboard_name=\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "Rates",
   "type": "table",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 69 },
   "fieldConfig": { "defaults": { "unit": "Mbits" } },
   "targets": [
    {
     "expr": "mktxp_interface_rate{routerboard_name=\"$node\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  {
   "title": "POE",
   "type": "table",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 76 },
   "targets": [
    {
     "expr": "mktxp_poe_info{routerboard_name=\"$node\"}"
    }
   ]
  },
  {
   "title": "Interfaces",
   "type": "table",
   "description": "Status link/states: The current operational state of the interface",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "ifPhysAddress{instance='$instance'}"
    },
    {
     "expr": "ifOperStatus{instance='$instance'}"
    },
    {
     "expr": "mtxrInterfaceStatsRxBytes{instance='$instance'}"
    },
    {
     "expr": "mtxrInterfaceStatsTxBytes{instance='$instance'}"
    },
    { "expr": "ifSpeed{instance='$instance'}" },
    {
     "expr": "mtxrInterfaceStatsLinkDowns{instance='$instance'}"
    },
    { "expr": "ifMtu{instance='$instance'}" },
    {
     "expr": "ifType_info{instance='$instance'}"
    },
    {
     "expr": "mtxrPOEInterfaceIndex{instance='$instance'}"
    },
    { "expr": "ifAlias{instance='$instance'}" }
   ]
  },
  {
   "title": "Interface traffic ",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 90 },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_interface_rx_byte_total{routerboard_name=\"$node\"}[4m])*8",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "In | {{ name }}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_interface_tx_byte_total{routerboard_name=\"$node\"}[4m])*8",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Outgoing traffic on interface ether1-gateway"
     },
     "legendFormat": "Out | {{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "MTU",
   "type": "timeseries",
   "description": "Maximum Transmission Unit",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 104 },
   "targets": [
    { "expr": "ifMtu{instance='$instance'}", "legendFormat": "{{ifName}}" }
   ]
  },
  { "title": "Firewall", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 110 } },
  {
   "title": "All Addresses Lists",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 111 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mktxp_firewall_filter_total{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "/errors on interface/" },
     "legendFormat": "{{count_type}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Selected Addresses Lists",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 111 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mktxp_firewall_mangle_total{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": { "filter": "/errors on interface/" },
     "legendFormat": "{{list}}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Firewall Address Lists",
   "type": "table",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 111 },
   "fieldConfig": { "defaults": { "unit": "bool_yes_no" } },
   "targets": [
    {
     "expr": "mktxp_firewall_address_list{routerboard_name=\"$node\"}"
    }
   ]
  },
  {
   "title": "Open Connections",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mktxp_connection_stats{routerboard_name=\"$node\"}"
    }
   ]
  },
  {
   "title": "Open Connections Stats",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "last_over_time(mktxp_connection_stats{routerboard_name=\"$node\"}[$__rate_interval])",
     "legendFormat": "{{dhcp_name}}"
    }
   ]
  },
  {
   "title": "Logged Firewall Rules Traffic ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 125 },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_firewall_filter_total{routerboard_name=\"$node\", log=\"1\"}[4m])*8",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Logged Raw Firewall Rules Traffic ",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 125 },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_firewall_raw_total{routerboard_name=\"$node\", log=\"1\"}[4m])*8",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Firewall Rules Traffic ",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 137 },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_firewall_filter_total{routerboard_name=\"$node\"}[4m])*8",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Raw Firewall Rules Traffic ",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 137 },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_firewall_raw_total{routerboard_name=\"$node\"}[4m])*8",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  { "title": "Netwatch", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 151 } },
  {
   "title": "Host Status History",
   "type": "state-timeline",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 152 },
   "targets": [
    {
     "expr": "mktxp_netwatch_status{name=\"8.8.8.8\", routerboard_name=\"$node\"}",
     "legendFormat": "WAN"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"1.1.1.1\", routerboard_name=\"$node\"}",
     "legendFormat": "WAN-2"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"10.10.10.2\", routerboard_name=\"$node\"}",
     "legendFormat": "Server1"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"10.20.20.2\", routerboard_name=\"$node\"}",
     "legendFormat": "Server2"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"10.20.20.3\", routerboard_name=\"$node\"}",
     "legendFormat": "AMP"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"10.30.30.10\", routerboard_name=\"$node\"}",
     "legendFormat": "iDRAC1"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"10.30.30.11\", routerboard_name=\"$node\"}",
     "legendFormat": "iDRAC2"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"10.60.60.200\", routerboard_name=\"$node\"}",
     "legendFormat": "mAP2nD-1"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"10.60.60.201\", routerboard_name=\"$node\"}",
     "legendFormat": "wAP2nD-1"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"10.40.40.2\", routerboard_name=\"$node\"}",
     "legendFormat": "RPi"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"172.17.0.2\", routerboard_name=\"$node\"}",
     "legendFormat": "Pi-hole"
    }
   ]
  },
  {
   "title": "Wireless",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 158 },
   "collapsed": true,
   "panels": [
    {
     "title": "Noise Floor",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "dB" } },
     "targets": [
      {
       "expr": "mktxp_wlan_noise_floor{routerboard_name=\"$node\"}",
       "legendFormat": "{{channel}}"
      }
     ]
    },
    {
     "title": "Overall Tx CCQ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 117 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "mktxp_wlan_overall_tx_ccq{routerboard_name=\"$node\"}",
       "legendFormat": "{{channel}}"
      }
     ]
    },
    {
     "title": "Client Devices",
     "type": "table",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 125 },
     "targets": [
      {
       "expr": "mktxp_wlan_clients_devices_info{routerboard_name=\"$node\"}"
      }
     ]
    },
    {
     "title": "Number of clients",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 125 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "mktxp_wlan_registered_clients{routerboard_name=\"$node\"}",
       "legendFormat": "{{channel}}"
      }
     ]
    },
    {
     "title": "WLAN Clients Tx CCQ",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "mktxp_wlan_clients_tx_ccq{routerboard_name=\"$node\"}",
       "legendFormat": "{{dhcp_name}}"
      }
     ]
    },
    {
     "title": "Clients Traffic",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 133 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_wlan_clients_tx_bytes_total{routerboard_name=\"$node\"}[4m])",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "In - {{ dhcp_name }}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_wlan_clients_rx_bytes_total{routerboard_name=\"$node\"}[4m])",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Outgoing traffic on interface ether1-gateway"
       },
       "legendFormat": "Out - {{ dhcp_name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Clients Signal Strength",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "dB" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "mktxp_wlan_clients_signal_strength{routerboard_name=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ dhcp_name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Clients  Signal-to-Noise ",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 141 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "mktxp_wlan_clients_signal_to_noise{routerboard_name=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ dhcp_name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  },
  { "title": "CAPsMAN", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 159 } },
  {
   "title": "Remote Caps",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 160 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "mktxp_capsman_remote_caps_info{routerboard_name=\"$node\"}",
     "legendFormat": "{{identity}}"
    }
   ]
  },
  {
   "title": "CAPsMAN Clients",
   "type": "table",
   "gridPos": { "h": 15, "w": 18, "x": 6, "y": 160 },
   "targets": [
    {
     "expr": "mktxp_capsman_clients_devices_info{routerboard_name=\"$node\"}"
    }
   ]
  },
  {
   "title": "CAPsMAN Registrations",
   "type": "bargauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 166 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mktxp_capsman_registrations_count{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ interface }}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "sum(mktxp_capsman_registrations_count{routerboard_name=\"$node\"})",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Registered Client Signal Strength",
   "type": "bargauge",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 173 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mktxp_capsman_clients_signal_strength{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ dhcp_name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CAPsMan Clients Signal Strength",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 18, "x": 6, "y": 175 },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "mktxp_capsman_clients_signal_strength{routerboard_name=\"$node\"}",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ dhcp_name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "CAPsMAN Clients Traffic",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 184 },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_capsman_clients_tx_bytes_total{routerboard_name=\"$node\"}[4m])*8",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "In | {{ dhcp_name }}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_capsman_clients_rx_bytes_total{routerboard_name=\"$node\"}[4m])*8",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Outgoing traffic on interface ether1-gateway"
     },
     "legendFormat": "Out | {{ dhcp_name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "Simple Queue",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 194 },
   "collapsed": true,
   "panels": [
    {
     "title": "Simple Queue Rates",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "mktxp_queue_simple_rates_download_total{routerboard_name=\"$node\"}*8",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }} Download",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "Network" },
       "expr": "mktxp_queue_simple_rates_upload_total{routerboard_name=\"$node\"}*8",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }} Upload",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Simple Queue Processed Bytes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 153 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "mktxp_queue_simple_bytes_download_total{routerboard_name=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }} Download",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "Network" },
       "expr": "mktxp_queue_simple_bytes_upload_total{routerboard_name=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }} Upload",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Simple Queue Queued Bytes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 212 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_queue_simple_queued_bytes_upload_total{routerboard_name=\"$node\"}[4m])",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }} Download",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_queue_simple_queued_bytes_upload_total{routerboard_name=\"$node\"}[4m])",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }} Upload",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Simple Queue Dropped Bytes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 212 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_queue_simple_dropped_download_total{routerboard_name=\"$node\"}[4m])",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }} Download",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_queue_simple_dropped_upload_total{routerboard_name=\"$node\"}[4m])",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }} Upload",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Queue Tree",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 195 },
   "collapsed": true,
   "panels": [
    {
     "title": "Queue Tree Rates",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "bps" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "mktxp_queue_tree_rates_total{routerboard_name=\"$node\"}*8",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Queue Tree Processed Bytes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 154 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "mktxp_queue_tree_bytes_total{routerboard_name=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Queue Tree Queued Bytes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 0, "y": 191 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_queue_tree_queued_bytes_total{routerboard_name=\"$node\"}[4m])",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Queue Tree Dropped Bytes",
     "type": "timeseries",
     "gridPos": { "h": 11, "w": 12, "x": 12, "y": 191 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_queue_tree_dropped_total{routerboard_name=\"$node\"}[4m])",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  },
  {
   "title": "Kid Control Devices",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 196 },
   "collapsed": true,
   "panels": [
    {
     "title": "Connected Devices",
     "type": "table",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 155 },
     "targets": [
      {
       "expr": "mktxp_kid_control_device_info{routerboard_name=\"$node\"}"
      }
     ]
    },
    {
     "title": "Transfer Rates",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 155 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "mktxp_kid_control_device_rate_down{routerboard_name=\"$node\"}*8",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "Down | {{ dhcp_name }}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "expr": "mktxp_kid_control_device_rate_up{routerboard_name=\"$node\"}*8",
       "legendFormat": "Up | {{ dhcp_name }}"
      }
     ]
    },
    {
     "title": "Idle Times",
     "type": "bargauge",
     "gridPos": { "h": 13, "w": 12, "x": 0, "y": 168 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "mktxp_kid_control_device_idle_time{routerboard_name=\"$node\"}",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "{{ dhcp_name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    },
    {
     "title": "Data Transfers",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 12, "x": 12, "y": 168 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_kid_control_device_bytes_down_total{routerboard_name=\"$node\"}[4m])*8",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Incoming traffic on interface ether1-gateway"
       },
       "legendFormat": "In | {{ name }}",
       "options": {
        "showDisabledItems": false
       }
      },
      {
       "application": { "filter": "Network" },
       "expr": "rate(mktxp_kid_control_device_bytes_up_total{routerboard_name=\"$node\"}[4m])*8",
       "group": { "filter": "Network" },
       "host": { "filter": "MikroTik Router" },
       "item": {
        "filter": "Outgoing traffic on interface ether1-gateway"
       },
       "legendFormat": "Out | {{ name }}",
       "options": {
        "showDisabledItems": false
       }
      }
     ]
    }
   ]
  },
  { "title": "MKTXP Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 197 } },
  {
   "title": "MKTXP Collection Times",
   "type": "bargauge",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 198 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_collection_time_total{routerboard_name=\"$node\"}[4m])  ",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ name }}",
     "options": {
      "showDisabledItems": false
     }
    }
   ]
  },
  {
   "title": "MKTXP Collection Times",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 198 },
   "targets": [
    {
     "application": { "filter": "Network" },
     "expr": "rate(mktxp_collection_time_total{routerboard_name=\"$node\"}[4m])",
     "group": { "filter": "Network" },
     "host": { "filter": "MikroTik Router" },
     "item": {
      "filter": "Incoming traffic on interface ether1-gateway"
     },
     "legendFormat": "{{ name }}",
     "options": {
      "showDisabledItems": false
     }
    },
    {
     "expr": "sum(rate(mktxp_collection_time_total{routerboard_name=\"$node\"}[4m]))",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "CAPsMAN client count",
   "type": "stat",
   "description": "Wireless registration table entry count",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 206 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mtxrWlCMRtabEntryCount{instance='$instance'}"
    }
   ]
  },
  {
   "title": "Total SNMP time",
   "type": "stat",
   "description": "Total SNMP time scrape took (walk and processing)",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 206 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_scrape_duration_seconds{instance='$instance'}"
    }
   ]
  },
  {
   "title": "Neighbors",
   "type": "table",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 206 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "mktxp_neighbor_info{routerboard_name=\"$node\"}"
    }
   ]
  },
  {
   "title": "PDUs returned",
   "type": "stat",
   "description": "PDUs returned from walk",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 209 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_scrape_pdus_returned{instance='$instance'}"
    }
   ]
  },
  {
   "title": "Time SNMP walk",
   "type": "stat",
   "description": "Time SNMP walk/bulkwalk took",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 209 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "snmp_scrape_walk_duration_seconds{instance='$instance'}"
    }
   ]
  },
  { "title": "Interfaces Traffic", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 212 } },
  {
   "title": "Traffic \"$Interface\"",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 213 },
   "repeat": "Interface",
   "targets": [
    {
     "expr": "irate(ifHCInOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
     "legendFormat": "In"
    },
    {
     "expr": "irate(ifHCOutOctets{ifName=~'$Interface',instance='$instance'}[$__rate_interval])*8",
     "legendFormat": "Out"
    }
   ]
  },
  {
   "title": "Multicast / Unicast / Errors etc.",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 290 }
  },
  {
   "title": "Interface \"$Interface\"",
   "type": "timeseries",
   "description": "Showing values > 0",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 291 },
   "repeat": "Interface",
   "targets": [
    {
     "expr": "irate(mtxrInterfaceStatsRxMulticast{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "In Multicast"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxMulticast{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Out Multicast"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxBroadcast{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "In Broadcast"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxBroadcast{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Out Broadcast"
    },
    {
     "expr": "irate(ifHCInUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "In Unicast"
    },
    {
     "expr": "irate(ifHCOutUcastPkts{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Out Unicast"
    },
    {
     "expr": "irate(ifInDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "In Discard"
    },
    {
     "expr": "irate(ifOutDiscards{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Out Discard"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxCodeError{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "In Errors"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxCodeError{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Out Errors"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxUnknownOp{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "In Unknown Protos"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxLengthError{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Out queue length"
    }
   ]
  },
  {
   "title": "Tx Eth errors, etc",
   "type": "timeseries",
   "description": "Showing values > 0",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 298 },
   "targets": [
    {
     "expr": "irate(mtxrInterfaceStatsTxControl{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Control - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxDeferred{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Deferred - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxCollision{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Collision - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxDrop{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Drop - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxExcessiveCollision{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Excessive Collision - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxExcessiveDeferred{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Excessive Deferred - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxFCSError{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx FCS Error - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxFragment{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Fragment - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxJabber{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Jabber - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxLateCollision{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Late Collision - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxMultipleCollision{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Multiple Collision - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxPause{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Pause - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxPauseHonored{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Pause Honored - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxSingleCollision{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Single Collision - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxTooLong{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Too Long - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxTooShort{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Too Short - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxTotalCollision{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Total Collision - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsTxUnderrun{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Tx Under run - {{ifName}}"
    }
   ]
  },
  {
   "title": "Rx Eth errors, etc",
   "type": "timeseries",
   "description": "Showing values > 0",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 298 },
   "targets": [
    {
     "expr": "irate(mtxrInterfaceStatsRxAlignError{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Align Error - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxCarrierError{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Carrier Error - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxControl{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Control - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxDrop{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Drop - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxFCSError{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "FCS Error - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxFragment{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Fragment - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxJabber{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Jabber - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxLengthError{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Length Error - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxOverflow{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Overflow - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxPause{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Pause - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxTooLong{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Too Long - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxTooShort{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Too Short - {{ifName}}"
    },
    {
     "expr": "irate(mtxrInterfaceStatsRxUnknownOp{ifName=~'$Interface',instance='$instance'}[$__rate_interval])",
     "legendFormat": "Rx Unknown Op - {{ifName}}"
    }
   ]
  }
 ]
}