{
 "title": "Prometheus — Scrape Health",
 "description": "Get started faster with Grafana Cloud then easily build these dashboards. https://grafana.com/products/cloud/\nOverview of metrics from Prometheus 2.0.  \nUseful for using prometheus to monitor your prometheus.\nRevisions welcome!",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5m",
 "templating": {
  "list": [
   { "name": "prom_ds", "label": "Prometheus", "query": "prometheus" },
   {
    "name": "job",
    "query": "query_result(prometheus_tsdb_head_samples_appended_total)"
   },
   {
    "name": "instance",
    "query": "query_result(up{job=~\"$job\"})"
   },
   {
    "name": "interval",
    "query": "1h, 3h, 6h, 12h, 1d, 2d, 7d, 30d, 90d, 180d"
   }
  ]
 },
 "panels": [
  { "title": "📡 NETWORK STATUS", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsLocalNoDateIfToday" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "time() * 1000" }
   ]
  },
  {
   "title": "Router Uptime",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "dtdurations" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "mktxp_system_uptime" }
   ]
  },
  {
   "title": "Hosts",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(mktxp_netwatch_status == 1)",
     "legendFormat": "UP"
    },
    {
     "expr": "count(mktxp_netwatch_status == 0)",
     "legendFormat": "DOWN"
    }
   ]
  },
  {
   "title": "📡 NETWORK STATUS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 12, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mktxp_netwatch_status{name=\"8.8.8.8\"}",
     "legendFormat": "WAN"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"1.1.1.1\"}",
     "legendFormat": "WAN-2"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"10.10.10.2\"}",
     "legendFormat": "Server1"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"10.20.20.2\"}",
     "legendFormat": "Server2"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"10.20.20.3\"}",
     "legendFormat": "AMP"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"10.30.30.10\"}",
     "legendFormat": "iDRAC1"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"10.30.30.11\"}",
     "legendFormat": "iDRAC2"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"10.60.60.200\"}",
     "legendFormat": "mAP2nD-1"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"10.60.60.201\"}",
     "legendFormat": "wAP2nD-1"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"10.40.40.2\"}",
     "legendFormat": "RPi"
    },
    {
     "expr": "mktxp_netwatch_status{name=\"172.17.0.2\"}",
     "legendFormat": "Pi-hole"
    }
   ]
  },
  { "title": "📊 At a Glance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Uptime [$interval]",
   "type": "stat",
   "description": "Percentage of uptime during the most recent $interval period.  Change the period with the 'interval' dropdown above.",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(avg_over_time(up{instance=~\"$instance\",job=~\"$job\"}[$interval]) * 100)"
    }
   ]
  },
  {
   "title": "Currently Down",
   "type": "stat",
   "description": "Servers which are DOWN RIGHT NOW! \nFIX THEM!!",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(up{instance=~\"$instance\",job=~\"$job\"} < 1) or vector(0)"
    }
   ]
  },
  {
   "title": "Total Series",
   "type": "stat",
   "description": "Total number of time series in prometheus",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_series{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  {
   "title": "Memory Chunks",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(prometheus_tsdb_head_chunks{job=~\"$job\",instance=~\"$instance\"})"
    }
   ]
  },
  { "title": "📋 Quick Numbers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 11 } },
  {
   "title": "Rule Eval Failures [$interval]",
   "type": "stat",
   "description": "The total number of rule group evaluations missed due to slow rule group evaluation.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_rule_evaluation_failures_total{job=~\"$job\",instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Body Size Exceeded [$interval]",
   "type": "stat",
   "description": "The total number of rule group evaluations skipped due to throttled metric storage.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_target_scrapes_exceeded_body_size_limit_total{job=~\"$job\",instance=~\"$instance\"}[$interval])) or vector(0)"
    }
   ]
  },
  {
   "title": "Tardy Scrapes [$interval]",
   "type": "stat",
   "description": "Total number of scrapes that hit the sample limit and were rejected.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_target_scrapes_exceeded_sample_limit_total{job=~\"$job\",instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Reload Failures [$interval]",
   "type": "stat",
   "description": "Number of times the database failed to reload block data from disk.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_tsdb_reloads_failures_total{job=~\"$job\",instance=~\"$instance\"}[$interval]))"
    }
   ]
  },
  {
   "title": "Skipped Scrapes [$interval]",
   "type": "stat",
   "description": "Sum of all skipped scrapes",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(sum_over_time(prometheus_target_scrapes_exceeded_sample_limit_total{job=~\"$job\",instance=~\"$instance\"}[$interval])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_duplicate_timestamp_total{job=~\"$job\",instance=~\"$instance\"}[$interval])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_out_of_bounds_total{job=~\"$job\",instance=~\"$instance\"}[$interval])) + \nsum(sum_over_time(prometheus_target_scrapes_sample_out_of_order_total{job=~\"$job\",instance=~\"$instance\"}[$interval])) "
    }
   ]
  },
  { "title": "⚠️ Errors", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Failures and Errors",
   "type": "timeseries",
   "description": "All non-zero failures and errors",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(increase(prometheus_rule_evaluation_failures_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "rule eval failures"
    },
    {
     "expr": "sum(increase(prometheus_sd_dns_lookup_failures_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "dns lookup failures"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_exceeded_sample_limit_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "sample limit exceeded"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_duplicate_timestamp_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "duplicate timestamps"
    },
    {
     "expr": "sum(increase(prometheus_target_scrapes_sample_out_of_order_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "out of order"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_compactions_failed_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "compaction failures"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_reloads_failures_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "reload failures"
    },
    {
     "expr": "sum(increase(prometheus_tsdb_head_series_not_found{instance=~\"$instance\"}[5m]))",
     "legendFormat": "series not found"
    },
    {
     "expr": "sum(increase(net_conntrack_dialer_conn_failed_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "connection failures"
    }
   ]
  },
  { "title": "✅ Upness", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Upness (stacked)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "up{instance=~\"$instance\",job=~\"$job\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Storage Memory Chunks",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_chunks{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "📈 Series", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Series Count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "prometheus_tsdb_head_series{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Series Created / Removed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "targets": [
    {
     "expr": "sum( increase(prometheus_tsdb_head_series_created_total{instance=~\"$instance\"}[5m]) )",
     "legendFormat": "created"
    },
    {
     "expr": "sum( increase(prometheus_tsdb_head_series_removed_total{instance=~\"$instance\"}[5m]) )",
     "legendFormat": "removed"
    }
   ]
  },
  { "title": "📥 Appended Samples", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 40 } },
  {
   "title": "Appended Samples per Second",
   "type": "timeseries",
   "description": "Rate of total number of appended samples",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 41 },
   "targets": [
    {
     "expr": "rate(prometheus_tsdb_head_samples_appended_total{job=~\"$job\",instance=~\"$instance\"}[1m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "🔄 Sync", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 48 } },
  {
   "title": "Scrape Sync Total",
   "type": "timeseries",
   "description": "Total number of syncs that were executed on a scrape pool.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
   "targets": [
    {
     "expr": "sum(prometheus_target_scrape_pool_sync_total{job=~\"$job\",instance=~\"$instance\"}) by (scrape_job)",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  {
   "title": "Target Sync",
   "type": "timeseries",
   "description": "Actual interval to sync the scrape pool.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
   "targets": [
    {
     "expr": "sum(rate(prometheus_target_sync_length_seconds_sum{job=~\"$job\",instance=~\"$instance\"}[2m])) by (scrape_job) * 1000",
     "legendFormat": "{{scrape_job}}"
    }
   ]
  },
  { "title": "🔍 Scrapes", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 56 } },
  {
   "title": "Scrape Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 57 },
   "targets": [
    {
     "expr": "scrape_duration_seconds{instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Rejected Scrapes",
   "type": "timeseries",
   "description": "Total number of rejected scrapes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 57 },
   "targets": [
    {
     "expr": "sum(prometheus_target_scrapes_exceeded_sample_limit_total{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "exceeded sample limit"
    },
    {
     "expr": "sum(prometheus_target_scrapes_sample_duplicate_timestamp_total{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "duplicate timestamp"
    },
    {
     "expr": "sum(prometheus_target_scrapes_sample_out_of_bounds_total{job=~\"$job\",instance=~\"$instance\"})",
     "legendFormat": "out of bounds"
    },
    {
     "expr": "sum(prometheus_target_scrapes_sample_out_of_order_total{job=~\"$job\",instance=~\"$instance\"}) ",
     "legendFormat": "out of order"
    }
   ]
  },
  { "title": "⏱ Durations", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 64 } },
  {
   "title": "Average Rule Evaluation Duration",
   "type": "timeseries",
   "description": "The duration of rule group evaluations",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 65 },
   "targets": [
    {
     "expr": "1000 * rate(prometheus_rule_evaluation_duration_seconds_sum{job=~\"$job\", instance=~\"$instance\"}[5m]) / rate(prometheus_rule_evaluation_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "HTTP Request Duration",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 65 },
   "targets": [
    {
     "expr": "sum(rate(prometheus_http_request_duration_seconds_count{job=~\"$job\",instance=~\"$instance\"}[1m])) by (handler) > 0",
     "legendFormat": "{{handler}}"
    }
   ]
  },
  {
   "title": "Prometheus Engine Query Duration Seconds",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 72 },
   "targets": [
    {
     "expr": "sum(prometheus_engine_query_duration_seconds_sum{job=~\"$job\",instance=~\"$instance\"}) by (slice)",
     "legendFormat": "{{slice}}"
    }
   ]
  },
  {
   "title": "Rule Evaluations Rate",
   "type": "timeseries",
   "description": "Rule-group evaluations \n - total\n - missed due to slow rule group evaluation\n - skipped due to throttled metric storage",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 72 },
   "targets": [
    {
     "expr": "sum(rate(prometheus_rule_evaluation_duration_seconds_count{job=~\"$job\", instance=~\"$instance\"}[5m]))",
     "legendFormat": "evaluations/s"
    }
   ]
  },
  { "title": "🔔 Notifications", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 79 } },
  {
   "title": "Notifications Sent",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 80 },
   "targets": [
    {
     "expr": "rate(prometheus_api_notification_updates_sent_total{job=~\"$job\", instance=~\"$instance\"}[5m])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "⚙️ Config", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 87 } },
  {
   "title": "Minutes Since Successful Config Reload",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 88 },
   "targets": [
    {
     "expr": "(time() - prometheus_config_last_reload_success_timestamp_seconds{job=~\"$job\",instance=~\"$instance\"}) / 60",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Successful Config Reload",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 88 },
   "targets": [
    {
     "expr": "prometheus_config_last_reload_successful{job=~\"$job\",instance=~\"$instance\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  { "title": "🗑 Garbage Collection", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 95 } },
  {
   "title": "GC Rate / 2m",
   "type": "timeseries",
   "description": "GC invocation durations",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 96 },
   "targets": [
    {
     "expr": "sum(rate(go_gc_duration_seconds_sum{instance=~\"$instance\",job=~\"$job\"}[2m])) by (instance)",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}